# Generated by Django 2.2.6 on 2019-11-14 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview_exp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='role_Type',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Full Time', 'Full Time')], default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiences',
            name='verification_Status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Review Pending', 'Review Pending'), ('Changes Requested', 'Changes Requested')], default='Review Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='experiences',
            name='verifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='interview_Questions',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.CreateModel(
            name='Revisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interview_exp.Experiences')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Revisions',
                'db_table': 'revisions',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
