# Generated by Django 2.2.6 on 2019-11-11 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=30)),
                ('topics', models.TextField()),
                ('teacher', models.CharField(blank=True, max_length=30, null=True)),
                ('material_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Class',
                'db_table': 'class',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contest_url', models.URLField(blank=True, null=True)),
                ('editorial_url', models.URLField(blank=True, null=True)),
                ('ranklist_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contests',
                'db_table': 'contests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('event_type', models.CharField(choices=[('1', 'contest'), ('2', 'class'), ('3', 'other')], default='3', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_topics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Class')),
                ('contest_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Contests')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'managed': True,
            },
        ),
    ]
