# Generated by Django 2.2.6 on 2019-11-11 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20191111_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_and_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('tester', 'tester'), ('setter', 'setter'), ('rank1', 'rank1'), ('rank2', 'rank2'), ('rank3', 'rank3')], default='tester', max_length=50)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Events')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Events_and_users',
                'db_table': 'events_and_users',
                'managed': True,
            },
        ),
    ]
