# Generated by Django 2.2.6 on 2019-11-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_and_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_and_users',
            name='user_type',
            field=models.CharField(choices=[('tester', 'tester'), ('setter', 'setter'), ('teacher', 'teacher'), ('rank1', 'rank1'), ('rank2', 'rank2'), ('rank3', 'rank3')], default='tester', max_length=50),
        ),
    ]
