# Generated by Django 2.2.6 on 2020-03-05 12:35

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.CreateModel(
            name='Event_contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Contests')),
                ('event_title', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Events')),
            ],
            options={
                'verbose_name_plural': 'Event_contest',
                'db_table': 'event_contest',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_topics', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Class')),
                ('event_title', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Events')),
            ],
            options={
                'verbose_name_plural': 'Event_class',
                'db_table': 'event_class',
                'managed': True,
            },
        ),
    ]
