# Generated by Django 2.2.6 on 2020-03-05 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200305_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='class_topics',
        ),
        migrations.RemoveField(
            model_name='events',
            name='contest_name',
        ),
        migrations.AlterField(
            model_name='event_class',
            name='class_topics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Class'),
        ),
        migrations.AlterField(
            model_name='event_class',
            name='event_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Events'),
        ),
        migrations.AlterField(
            model_name='event_contest',
            name='contest_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Contests'),
        ),
        migrations.AlterField(
            model_name='event_contest',
            name='event_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Events'),
        ),
    ]
