# Generated by Django 2.2.6 on 2020-03-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200305_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Events'),
        ),
        migrations.AddField(
            model_name='contests',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Events'),
        ),
    ]
