# Generated by Django 2.2.6 on 2020-03-06 04:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0011_auto_20200305_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_and_users',
            new_name='Contest_and_users',
        ),
        migrations.AlterModelOptions(
            name='contest_and_users',
            options={'managed': True, 'verbose_name_plural': 'Contest_and_users'},
        ),
        migrations.AlterModelTable(
            name='contest_and_users',
            table='contest_and_users',
        ),
    ]
