# Generated by Django 2.2.6 on 2020-03-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_class_and_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_and_users',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'teacher'), ('coordinator', 'coordinator')], default='teacher', max_length=50),
        ),
        migrations.AlterField(
            model_name='contest_and_users',
            name='user_type',
            field=models.CharField(choices=[('tester', 'tester'), ('setter', 'setter'), ('rank1', 'rank1'), ('rank2', 'rank2'), ('rank3', 'rank3')], default='tester', max_length=50),
        ),
    ]
