# Generated by Django 2.2.6 on 2020-03-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20200306_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_and_users',
            old_name='user_type',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='class_and_users',
            old_name='user',
            new_name='name',
        ),
    ]
