# Generated by Django 2.2.6 on 2020-03-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20200306_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_contest',
            name='contest_name',
        ),
        migrations.RemoveField(
            model_name='event_contest',
            name='event_title',
        ),
        migrations.DeleteModel(
            name='Event_class',
        ),
        migrations.DeleteModel(
            name='Event_contest',
        ),
    ]
