# Generated by Django 2.2.6 on 2020-03-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20200306_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest_and_users',
            name='rank1',
        ),
        migrations.RemoveField(
            model_name='contest_and_users',
            name='rank2',
        ),
        migrations.RemoveField(
            model_name='contest_and_users',
            name='rank3',
        ),
        migrations.AddField(
            model_name='contests',
            name='rank1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contests',
            name='rank2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contests',
            name='rank3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
